[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "api"
  node_bundler = "esbuild"
  external_node_modules = ["./node_modules"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 3000
  framework = "nextjs"